name: Publish to PyPi

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install

    - name: Setup pypi connection
      run: |
        poetry config repositories.pyneuphonic https://upload.pypi.org/legacy/
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Publish package
      run: |
        poetry publish --build --repository pyneuphonic
