name: Windows tests

# This file is meant for testing across supported Python versions.

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

    - name: Install dependencies
      run: |
        & "$env:APPDATA\Python\Scripts\poetry" install

    - name: Test with pytest
      run: |
        & "$env:APPDATA\Python\Scripts\poetry" run pytest --cov pyneuphonic

    - name: Lint with ruff
      run: |
        & "$env:APPDATA\Python\Scripts\poetry" run ruff check .
